DROP TABLE IF EXISTS film_likes;
DROP TABLE IF EXISTS user_friends;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email VARCHAR(255) NOT NULL,
	login VARCHAR(255) NOT NULL,
	name VARCHAR(255) NOT NULL,
	birthdate DATE
);

CREATE TABLE user_friends (
	user_id BIGINT REFERENCES users (user_id),
	friend_id BIGINT REFERENCES users (user_id)
);

CREATE TABLE films (
	film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	description VARCHAR(200),
	duration INTEGER,
	release_date DATE,
	rating_mpa BIGINT,
	CONSTRAINT positive_duration CHECK (duration > 0)
);

CREATE TABLE genres (
	genre_id BIGINT PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE ratings (
	rating_id BIGINT PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE film_genre (
	film_id BIGINT REFERENCES films (film_id),
	genre_id BIGINT REFERENCES genres (genre_id)
);

CREATE TABLE film_likes (
	film_id BIGINT REFERENCES films (film_id),
	user_id BIGINT REFERENCES users (user_id)
);